WIP: Major refactor

diff --git a/lib/container/index b/lib/container/index
--- a/lib/container/index
+++ b/lib/container/index
@@ -1,25 +1,117 @@
 #!/usr/bin/env bash
 
-services="$1"
+__service_names=() && __service_definitions=()
 
-names=() && definitions=()
-
-__container_add() {
+##
+# Add items to the container
+#
+# The first argument should be the name of the item. The remaining arguments are
+# all treated as sequential. However, in the case of a service that points to a
+# script or file, the first of the remaining arguments is treated as the file
+# path/location and, the remaining arguments, as its input arguments.
+##
+container::add() {
     local name="$1" && shift
     local definition="$@"
 
-    names+=("$name")
-    definitions+=("$definition")
+    __service_names+=("$name")
+    __service_definitions+=("$definition")
 }
 
-__container_get() {
-    local name="$1" && shift
+##
+# Gets the name and any existing suffix for a given service alias.
+##
+__container::get_alias_name_and_suffix() {
+    local name="$1"
+    local service_alias
 
-    for key in ${!names[*]}; do
-        if [[ $name == ${names[$key]} ]]; then
-            echo "${definitions[$key]}" && exit 0
+    # TODO: handle multiple joined aliases?
+    if [[ "$name" =~ ^@(.*)::(.*)$ ]]; then
+        # name is an alias joined by a suffix, separated by '::' - i.e.:
+        # '@example-parameter::example-suffix'
+        service_alias=("${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}")
+    elif [[ "$name" =~ ^@(.*)$ ]]; then
+        # name is an alias without a suffix - i.e.: '@example-service'
+        service_alias=("${BASH_REMATCH[1]}")
+    fi
+
+    echo ${service_alias[*]}
+}
+
+##
+# Get the definition of a given parameter or service
+##
+container::get_definition() {
+    local name="$1"
+    local service_alias=$(__container::get_alias_name_and_suffix "$name")
+
+    if [[ -n "$service_alias" ]]; then
+        name="${service_alias[0]}"
+    fi
+
+    for key in ${!__service_names[*]}; do
+        if [[ $name == ${__service_names[$key]} ]]; then
+            echo "${__service_definitions[$key]}" && exit 0
         fi
     done
 
     echo "Error: No definition exists for the '$name' service." && exit 1
+}
+
+##
+# Recursively resolves the definition of a given parameter, optionally returning
+# option handles for each named service defined as a dependency.
+##
+container::resolve() {
+    local name="$1"
+    local optionHandles=${2:-false}
+    local depth=${3:-0}
+
+    local suffix
+
+    local service_alias=$(__container::get_alias_name_and_suffix "$name")
+    if [[ -n "$service_alias" ]]; then
+        name="${service_alias[0]}"
+        suffix="${service_alias[1]}"
+    fi
+
+    for key in ${!__service_names[*]}; do
+        if [[ ${__service_names[$key]} != "$name" ]]; then
+            continue
+        fi
+
+        local defined
+        local switch
+
+        if $optionHandles; then
+            # add an argument handle to resolved service value
+            [[ $depth > 0 ]] && switch="--$name "
+        fi
+
+        for definition in $(container::get_definition "$name"); do
+            local args=("$definition" $optionHandles $(( $depth + 1 )))
+
+            defined="$(container::resolve ${args[*]})"
+
+            if [[ $? -eq 1 ]]; then
+                # container::get_definition threw an error, meaning that no
+                # service was found for the definition; we'll just use its
+                # current value
+                defined="$definition"
+            fi
+
+            if ! $optionHandles && [[ "$defined" =~ ^--\s*(.*) ]]; then
+                defined="${BASH_REMATCH[1]}"
+            fi
+
+            echo "${switch}${defined}${suffix}"
+
+            unset switch
+            unset args
+        done
+
+        exit 0 # exit here because the name has been matched
+    done
+
+    echo "Error: The '$name' service cannot be resolved." && exit 1
 }
diff --git a/src/bus/message-bus b/src/bus/message-bus
--- a/src/bus/message-bus
+++ b/src/bus/message-bus
@@ -1,47 +1,56 @@
 #!/usr/bin/env bash
 
-messages="$1"
-# TODO: should the target be configurable in the container?
-logger="$2 $3" && source $logger "$(tty)"
+__message_bus_message_dir=$(container::resolve "$1")
+__message_bus_logger=$(container::resolve "$2")
+__message_bus_routing=$(container::resolve "$3")
 
-shift 3
-routing="$@"
+source $__message_bus_logger
 
-if [[ ! -d "$messages" ]]; then
-    __log_error "An existing message directory is required" && exit 1
+# TODO: do we still need these; can we do them better?
+if [[ ! -d "$__message_bus_message_dir" ]]; then
+    log_slog::error "An existing message directory is required" && exit 1
 fi
 
-if [[ -z "$routing" ]]; then
-    __log_error "No message routing is defined" && exit 1
+if [[ -z "$__message_bus_routing" ]]; then
+    log_slog::error "No message routing is defined" && exit 1
 fi
 
-__dispatch_message() {
+##
+# Dispatches a message for an action via a given channel.
+##
+message_bus::dispatch_message() {
     local action="${1:-[empty]}"
 
-    local message="$messages/$(echo $action | tr '[:upper:]' '[:lower:]')-message"
+    local message="$__message_bus_message_dir/$(
+        echo $action | tr '[:upper:]' '[:lower:]'
+    )-message"
 
     if [[ ! -f "$message" ]]; then
-        __log_error "A message could not be found for the '$action' action."
+        log_slog::error "A message could not be found for the '$action' action."
         exit 1
     fi
 
-    local target
-    for route in ${routing[*]}; do
-        if [[ "$route" == "$message::"* ]]; then
-            target=$(echo "$route" | sed -E "s/.*::(.*)/\1/") && break;
+    local channel
+    for route in ${__message_bus_routing[*]}; do
+        # expected routing format:
+        # - path/2/action-message|/channel/to/write/2
+        if [[ "$route" =~ ^"$message"\|(.+)$ ]]; then
+            channel=${BASH_REMATCH[1]}
+            break
         fi
     done
 
-    if [[ -z "$target" ]]; then
-        __log_error "A message route is not defined for the '$action' message."
+    if [[ -z "$channel" ]]; then
+        log_slog::error "A message route is not defined for the '$action' message."
         exit 1
     fi
 
-    if [[ ! -e "$target" ]]; then
-        __log_error " The target '$target' does not exist." && exit 1
+    if [[ ! -e "$channel" ]] || [[ ! -w "$channel" ]]; then
+        log_slog::error "The channel '$channel' does not exist or is not writable."
+        exit 1
     fi
 
-    source $message && __send_message > $target
+    source $message && message::send_message > $channel
 
-    __log_info "'$action' message was dispatched."
+    log_slog::info "'$action' message was dispatched."
 }
diff --git a/src/handler/message-handler b/src/handler/message-handler
--- a/src/handler/message-handler
+++ b/src/handler/message-handler
@@ -1,25 +1,38 @@
 #!/usr/bin/env bash
 
-actions="$1"
-logger="$2 $3" && shift 3
+__message_handler_actions_dir=$(container::resolve "$1")
+__message_handler_logger=$(container::resolve "$2")
+__message_handler_bash_clash=$(container::resolve "$3")
 
-bash_clash="$@"
+source $__message_handler_logger
 
-source $logger "$(tty)"
-
-if [[ ! -d "$actions" ]]; then
-    __log_error "An existing actions directory is required" && exit 1
+if [[ ! -d "$__message_handler_actions_dir" ]]; then
+    log_slog::error "An existing actions directory is required" && exit 1
 fi
 
-__handle_message() {
+##
+# Gets the value of the --enquirer option from the given arguments
+##
+__message_handler::get_enquirer() {
+    echo $(
+        source "$__message_handler_bash_clash" $@ && bash_clash::get "enquirer"
+    )
+}
+
+##
+# Handles message pushed to a consumer pipe.
+#
+message_handler::handle_message() {
     local message="${1:-[EMPTY]}" && shift
     local args="$@"
-    local enquirer="$(source $bash_clash $args && echo $enquirer)"
 
-    action="$actions/$(echo $message | tr '[:upper:]' '[:lower:]')-action"
+    local enquirer=$(__message_handler::get_enquirer "$args")
+    local action="$__message_handler_actions_dir/$(
+        echo $message | tr '[:upper:]' '[:lower:]'
+    )-action"
 
     if [[ ! -f "$action" ]]; then
-        __log_error "An action could not be found for a '$message' message."
+        log_slog::error "An action could not be found for a '$message' message."
 
         # TODO: can we only use return statements, instead of exits (except
         # where absolutely necessary?)
@@ -27,10 +40,10 @@ __handle_message() {
     fi
 
     if [[ ! -w "$enquirer" ]]; then
-        __log_error "The enquirer '$enquirer' does not exist."
+        log_slog::error "The enquirer '$enquirer' does not exist."
 
         return 1 # return to continue execution
     fi
 
-    source $action && __process_action $args
+    source $action && action::process_action $args
 }
